[package]
name = "host"
version = "0.1.0"
edition = "2021"

[dependencies]
methods = { path = "../methods" }
risc0-zkvm = { version = "0.20" }
env_logger = "0.10"
serde = "1.0"
borsh = { version = "0.9", features = ["std"] }
bincode = "1.3.3"
hex = "0.4.3"
